version: "3"

volumes:
  database:
    driver: "local"
  nginx_logs:
    driver: "local"
  redis:
    driver: "local"

services:
  workspace:
    container_name: dockerhero_workspace
    image: johanvanhelden/dockerhero-workspace:php8.1
    volumes:
      - ./../:/var/www/projects
      - ./crons:/var/crons
      - /etc/localtime:/etc/localtime:ro
    tty: true
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.10

  php:
    container_name: dockerhero_php
    image: johanvanhelden/dockerhero-php-8.1-fpm:latest
    links:
      - db
      - workspace
      - redis
      - minio
    depends_on:
      - workspace
    volumes:
      - ../:/var/www/projects
      - ./.phpmyadmin/index.php:/var/www/phpmyadmin/index.php
      - ./.phpredisadmin/index.php:/var/www/phpredisadmin/index.php
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9912:9912"
    expose:
      - "9005"
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.11

  web:
    container_name: dockerhero_web
    image: johanvanhelden/dockerhero-nginx:latest
    links:
      - php
    volumes:
      - ../:/var/www/projects
      - ./.phpmyadmin/index.php:/var/www/phpmyadmin/index.php
      - ./.phpredisadmin/index.php:/var/www/phpredisadmin/index.php
      - ./nginx/conf:/etc/nginx/conf.d/dockerhero/custom
      - nginx_logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.12

  db:
    container_name: dockerhero_db
    image: mysql:5.7
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - "database:/var/lib/mysql"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dockerhero
      - MYSQL_PASSWORD=dockerhero
      - MYSQL_DATABASE=dockerhero
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    networks:
      dockerhero:
        ipv4_address: 172.25.0.13
    healthcheck:
      test: ["CMD", "mysqladmin", "-pdockerhero", "ping"]

  mail:
    container_name: dockerhero_mail
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      dockerhero:
        ipv4_address: 172.25.0.14

  redis:
    container_name: dockerhero_redis
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      dockerhero:
        ipv4_address: 172.25.0.15
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  phpmyadmin:
    container_name: dockerhero_dbadmin
    image: phpmyadmin
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      - ./.phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./databases:/var/www/html/tmp/dockerhero_databases
    environment:
      - PMA_HOST=dockerhero_db
      - PMA_ROOT_PASSWORD=dockerhero
      - PMA_USER=root
      - PMA_PASSWORD=dockerhero
      - MYSQL_ROOT_PASSWORD=dockerhero
      - MYSQL_PASSWORD=dockerhero
      - MYSQL_DATABASE=dockerhero
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    ports:
      - 8026:80
    networks:
      dockerhero:
        ipv4_address: 172.25.0.16

  phpredisadmin:
    container_name: dockerhero_redisadmin
    image: erikdubbelboer/phpredisadmin
    depends_on:
      - redis
    links:
      - redis
    restart: always
    environment:
      - REDIS_1_HOST=dockerhero_redis
      - REDIS_1_PORT=6379
    ports:
      - 8027:80
    networks:
      dockerhero:
        ipv4_address: 172.25.0.17

  minio:
    container_name: dockerhero_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=dockerhero
    image: minio/minio:latest
    ports:
      - '9001:9001'
      - '9000:9000'
    networks:
      dockerhero:
        ipv4_address: 172.25.0.18
    volumes:
      - ./minio:/data
    restart: unless-stopped

networks:
  dockerhero:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/17
